version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public
